version: "3.9"

services:
  backend:
    container_name: wine_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    # para poner las variables derecho sin usar .env
    # environment:
    #   - DATABASE_URL=${DATABASE_URL}
    #   - NODE_ENV=production
    restart: unless-stopped

  frontend:
    container_name: wine_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    # para el front necesita saber dónde está el backend VITE_API_URL:
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - backend
    restart: unless-stopped
